### ISSUE TITLE
Number of tags for s3 bucket object

### ISSUE THREAD

**Issue by Asvor** [terraform-aws-modules/terraform-aws-datadog-forwarders#24]
https://github.com/terraform-aws-modules/terraform-aws-datadog-forwarders/blob/752367fb8662f091b82ead776700f0fc1a3d06b5/modules/log_forwarder/main.tf#L147

The number of tags that can be attached to an s3 bucket object is 10 (for other resources it is 50) [Documentation](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-tagging.html)
So, we have an error: 
`Error: error updating tags: error setting resource tags (s-dd-forwarder-dev/aws-dd-forwarder-3.41.0.zip): BadRequest: Object tags cannot be greater than 10
	status code: 400, request id: TE64412FP9X2M6RM, host id: QshfEqkYz3YB1fcBPsmuqZ1jfFP3a3JegL4W5b+YPqD7Vck3FwZ8nvIewvdg4hrb+HTUdZS3q1I1bjEiZ/ZQBA==
  on .terraform/modules/datadog_log_forwarder/modules/log_forwarder/main.tf line 131, in resource "aws_s3_bucket_object" "this":
 131: resource "aws_s3_bucket_object" "this" {`

We need all these tags in other objects and we can't reduce them.

Could you, please, reduce or delete the number of tags in the module that can be attached to this object?

**Comment by bryantbiggs** [comment]
please fill out the issue template properly
