### ISSUE TITLE
S3 GetObject permission needs wildcard qualifier

### ISSUE THREAD

**Issue by berniedurfee-renaissance** [terraform-aws-modules/terraform-aws-datadog-forwarders#39]
Shouldn't the GetObject permission be `<bucket>/*` rather than just `<bucket>`?

https://github.com/terraform-aws-modules/terraform-aws-datadog-forwarders/blob/3920c116373537a1168d93889a9deb864d856bf7/modules/log_forwarder/policy.tmpl#L41

**Comment by berniedurfee-renaissance** [comment]
Or is the expectation that the

**Comment by berniedurfee-renaissance** [comment]
Or is the expectation that the bucket ARN will contain the `/*` part? If so, maybe that should be clarified in the documentation? I assumed the bucket ARN was just the ARN to the bucket, not to the objects.

**Comment by bryantbiggs** [comment]
> Or is the expectation that the bucket ARN will contain the /* part?

Correct - its up to users in terms of what level of access (via pathing/prefixing) they wish to provide permission on the forwarder
