### ISSUE TITLE
Terraform registry version is still 6.0.1

### ISSUE THREAD

**Issue by kimikimi714** [terraform-aws-modules/terraform-aws-datadog-forwarders#42]
## Description
Hello!
I would like to update this module to version [6.1.0](https://github.com/terraform-aws-modules/terraform-aws-datadog-forwarders/releases/tag/v6.1.0), but the latest version available on the [Terraform registry](https://registry.terraform.io/modules/terraform-aws-modules/datadog-forwarders/aws/latest) is still 6.0.1.
When I update my tf file and run `terraform init`, I get the following error:
> There is no available version of module "registry.terraform.io/terraform-aws-modules/datadog-forwarders/aws//modules/log_forwarder" (datadog_log_forwarder.tf:5) which matches the given
> version constraint. The newest available version is 6.0.1.

Could you update the version of Terraform registry?

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]: 6.1.0
- Terraform version: Terraform v1.9.0 on darwin_arm64
- Provider version(s):
    - + provider registry.terraform.io/hashicorp/aws v5.64.0
    - + provider registry.terraform.io/hashicorp/null v3.2.2
    - + provider registry.terraform.io/hashicorp/tls v4.0.5

## Reproduction Code [Required]

```
module "datadog_forwarders_log_forwarder" {
  source  = "terraform-aws-modules/datadog-forwarders/aws//modules/log_forwarder"
  version = "6.1.0"

  runtime                   = "python3.11"
  forwarder_version         = "3.122.0"
  dd_api_key_secret_arn     = data.aws_secretsmanager_secret.dd_api_key.arn
  log_forwarder_bucket_tags = {
    Sample = "tag"
  }
}
```

- Execute `terraform init`.

## Expected behavior

Finish without an error, like the example below (this example is for terraform-aws-modules/datadog-forwarders/aws 6.0.1):
```
❯ terraform init
Initializing the backend...
Initializing modules...
Downloading registry.terraform.io/terraform-aws-modules/datadog-forwarders/aws 6.0.1 for datadog_forwarders_log_forwarder...
- datadog_forwarders_log_forwarder in .terraform/modules/datadog_forwarders_log_forwarder/modules/log_forwarder
Downloading registry.terraform.io/terraform-aws-modules/s3-bucket/aws 3.6.1 for datadog_forwarders_log_forwarder.this_s3_bucket...
- datadog_forwarders_log_forwarder.this_s3_bucket in .terraform/modules/datadog_forwarders_log_forwarder.this_s3_bucket
Initializing provider plugins...
- Reusing previous version of hashicorp/null from the dependency lock file
- Reusing previous version of hashicorp/aws from the dependency lock file
- Reusing previous version of hashicorp/tls from the dependency lock file
- Using previously-installed hashicorp/null v3.2.2
- Using previously-installed hashicorp/aws v5.64.0
- Using previously-installed hashicorp/tls v4.0.5

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

## Actual behavior

```
❯ terraform init
Initializing the backend...
Initializing modules...
╷
│ Error: Unresolvable module version constraint
│ 
│   on datadog_log_forwarder.tf line 5:
│    5: module "datadog_forwarders_log_forwarder" {
│ 
│ There is no available version of module "registry.terraform.io/terraform-aws-modules/datadog-forwarders/aws//modules/log_forwarder" (datadog_log_forwarder.tf:5) which matches the given
│ version constraint. The newest available version is 6.0.1.
```

## Additional context

I'm using terraform-aws-datadog-forwarders module from registry.terraform.io . If there is a walk around, let me know.

**Comment by antonbabenko** [comment]
Fixed with magic stick :)

**Comment by kimikimi714** [comment]
<img width="890" alt="スクリーンショット 2024-08-29 10 22 27" src="https://github.com/user-attachments/assets/7d32ecc7-b129-4785-a70c-23af7c2ad79c">

Thank you!
