### ISSUE TITLE
KMS permissions should be tighter ?

### ISSUE THREAD

**Issue by internetstaff** [terraform-aws-modules/terraform-aws-datadog-forwarders#7]
The change here:

https://github.com/clowdhaus/terraform-aws-datadog-forwarders/commit/851257b02fc4be76236d5b5b48e3c8cf9b703098

... seems to grant the lambdas permission to kms:Decrypt on any KMS key, which seems bad from a security perspective?

Thanks!

**Comment by bryantbiggs** [comment]
I'm not saying there isn't room for improvement, but typically KMS keys set a resource policy which dictates who can do what with the key, while this statement here just states that the IAM role is allowed to make kms API calls - it would be up to the key resource policy to determine if the request should succeed or fail
